# Generated by Django 5.2.9 on 2025-12-05 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workerjob',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerjob',
            name='service_name',
            field=models.CharField(default='Home Service', max_length=100),
        ),
        migrations.AlterField(
            model_name='workerjob',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'user_type': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workerjob',
            unique_together={('worker', 'date', 'time')},
        ),
    ]
