# Generated by Django 5.2.9 on 2025-12-06 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_workerjob_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerjob',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='workerjob',
            index=models.Index(fields=['worker', 'date', 'time'], name='worker_work_worker__f88e63_idx'),
        ),
    ]
