# Generated by Django 5.2.9 on 2025-12-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
