# Generated by Django 5.2.9 on 2025-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_alter_invoice_hours_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerjob',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerjob',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerjob',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
