# Generated by Django 5.2.9 on 2025-12-08 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_workerjob_is_paid_workerjob_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='worker.workerjob'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'job')},
        ),
    ]
